return {
    Name = "Forest Dark",
    Accent = Color3.fromRGB(76, 175, 80),

    AcrylicMain = Color3.fromRGB(22, 28, 24),
    AcrylicBorder = Color3.fromRGB(40, 55, 45),
    AcrylicGradient = ColorSequence.new(Color3.fromRGB(20, 25, 22), Color3.fromRGB(15, 18, 16)),
    AcrylicNoise = 0.92,

    TitleBarLine = Color3.fromRGB(45, 60, 50),
    Tab = Color3.fromRGB(85, 107, 95),

    Element = Color3.fromRGB(45, 65, 55),
    ElementBorder = Color3.fromRGB(20, 28, 24),
    InElementBorder = Color3.fromRGB(45, 60, 50),
    ElementTransparency = 0.84,

    DropdownFrame = Color3.fromRGB(95, 125, 110),
    DropdownHolder = Color3.fromRGB(30, 40, 35),
    DropdownBorder = Color3.fromRGB(20, 28, 24),

    Dialog = Color3.fromRGB(30, 40, 35),
    DialogHolder = Color3.fromRGB(22, 28, 24),
    DialogHolderLine = Color3.fromRGB(18, 23, 20),
    DialogButton = Color3.fromRGB(30, 40, 35),
    DialogButtonBorder = Color3.fromRGB(45, 60, 50),
    DialogBorder = Color3.fromRGB(40, 55, 45),
    DialogInput = Color3.fromRGB(35, 48, 40),
    DialogInputLine = Color3.fromRGB(95, 125, 110)
}
